channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - click==7.1.2
  - cooler==0.8.9
  - Cython==0.29.21
  - numpy==1.19.1
  - pandas==1.1.0
  - ucsc-bedgraphtobigwig==377
  - pip:
      - cooltools==0.3.2
      - bioframe==0.0.12
